<a href="https://colab.research.google.com/github/Adarsha9845/Monte-Carlo-Simulation-/blob/main/MonteCarloTreeSearch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# a = np.array([[0, 0, 0], [2, 2, 2], [3, 3, 3]])
# if a[0][0] & a[0][1] & a[0][2] == 1 or 0:
#   print('Yess!')

In [ ]:
def identifyWin(state):
  a = state
  if a[0][0] & a[0][1] & a[0][2] == 1:
    return True, 'man'
  if a[0][0] & a[0][1] & a[0][2] == 2:
    return True, 'machine'

  if a[0][0] & a[1][0] & a[2][0] == 1:
    return True, 'man'
  if a[0][0] & a[1][0] & a[2][0] == 2:
    return True, 'machine'

  if a[0][1] & a[1][1] & a[2][1] == 1:
    return True, 'man'
  if a[0][1] & a[1][1] & a[2][1] == 2:
    return True, 'machine'

  if a[0][2] & a[1][2] & a[2][2] == 1:
    return True, 'man'
  if a[0][2] & a[1][2] & a[2][2] == 2:
    return True, 'machine'

  if a[1][0] & a[1][1] & a[1][2] == 1:
    return True, 'man'
  if a[1][0] & a[1][1] & a[1][2] == 2:
    return True, 'Machine'
  if a[2][0] & a[2][1] & a[2][2] == 1:
    return True, 'man'
  if a[2][0] & a[2][1] & a[2][2] == 2:
    return True, 'machine'
  if a[0][0] & a[1][1] & a[2][2] == 1:
    return True, 'man'
  if a[0][0] & a[1][1] & a[2][2] == 2:
    return True, 'machine'
  if a[0][2] & a[1][1] & a[2][0] == 1:
    return True, 'man'
  if a[0][2] & a[1][1] & a[2][0] == 2:
    return True, 'machine'
  else:
    return False, 'None'


In [ ]:
# a = np.array([[0, 0, 1], [1, 1, 0], [1, 1, 2]])
# stat = identifyWin(a)
# print(stat)

In [ ]:
def gamePlay(pos, cond, play_mode):
  if play_mode == 'man':
    cond[pos[0], pos[1]] = 1
    return cond
  else:
    cond[pos[0], pos[1]] = 2
    return cond
  # 1 is for human, 2 is for machine and 0 is unoccupied position

In [ ]:
# cond = np.array([[0, 0, 1], [1, 1, 0], [1, 1, 2]])
# pos = [1, 2]
# b = gamePlay(pos, cond, 'machine')

# print(b)

In [ ]:
# cond = np.array([[0, 0, 1], [1, 1, 0], [1, 1, 2]])
# for i in cond:
#   for j in i:
#     print(j)

In [ ]:
# cond = np.array([[0, 0, 1], [1, 1, 0], [1, 1, 2]])

In [ ]:
def randomPlay(cond, play_mode):
  a = 0
  possibleMove = []
  for i in cond:
    for j in i:
      if j == 0:
        possibleMove.append(a)
      a = a + 1
  move = np.random.choice(possibleMove)
  if move == 0:
    pos = [0, 0]

  if move == 1:
    pos = [0, 1]

  if move == 2:
    pos = [0, 2]

  if move == 3:
    pos = [1, 0]

  if move == 4:
    pos = [1, 1]

  if move == 5:
    pos = [1, 2]

  if move == 6:
    pos = [2, 0]

  if move == 7:
    pos = [2, 1]

  if move == 8:
    pos = [2, 2]
  cond = gamePlay(pos, cond, play_mode)
  return cond


In [ ]:
def randomPosGenerator(cond):
  a = 0
  possibleMove = []
  for i in cond:
    for j in i:
      if j == 0:
        possibleMove.append(a)
      a = a + 1
  move = np.random.choice(possibleMove)
  if move == 0:
    pos = [0, 0]

  if move == 1:
    pos = [0, 1]

  if move == 2:
    pos = [0, 2]

  if move == 3:
    pos = [1, 0]

  if move == 4:
    pos = [1, 1]

  if move == 5:
    pos = [1, 2]

  if move == 6:
    pos = [2, 0]

  if move == 7:
    pos = [2, 1]

  if move == 8:
    pos = [2, 2]

  return pos

In [ ]:
cond = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
cond

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
cond = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
count = 0
while True:
  cond = randomPlay(cond, 'machine')
  count = count + 1
  print(cond)
  status, who = identifyWin(cond)
  if status:
    if who == 'man':
      print('Man Won!!!')
      break
    else:
      print('Machine Won!!')
      break
  if count == 9:
    print('Match Draw!!')
    break
  pos = randomPosGenerator(cond)
  # pos = []
  # a = input('Your row')
  # b = input('Your column')

  # pos = [int(a), int(b)]
  print(pos)
  cond = gamePlay(pos, cond, play_mode = 'man')
  count = count + 1
  print(cond)
  status, who = identifyWin(cond)
  if status:
    if who == 'man':
      print('Man Won!!!')
      break
    else:
      print('Machine Won!!')
      break
  if count == 9:
    print('Match Draw!!')
    break





[[0 0 0]
 [0 0 2]
 [0 0 0]]
[1, 0]
[[0 0 0]
 [1 0 2]
 [0 0 0]]
[[0 0 2]
 [1 0 2]
 [0 0 0]]
[2, 0]
[[0 0 2]
 [1 0 2]
 [1 0 0]]
[[0 0 2]
 [1 0 2]
 [1 2 0]]
[0, 0]
[[1 0 2]
 [1 0 2]
 [1 2 0]]
Man Won!!!


In [ ]:
class nodes:
  def __init__(self, node_number, parent_number, parentVisit, layer, value = 0, totalVisit = 0):
    self.node_number = node_number
    self.parent_number = parent_number
    self.value = value
    self.totalVisit = totalVisit
    self.layer = layer
    self.parentVisit = parentVisit



In [ ]:
def calcUcb(node):
    if node.totalVisit == 0:
      ucb = 1000000
    else:
      ucb = node.value / node.totalVisit * (2)**0.5 * (np.log(node.parentVisit) / node.totalVisit) ** 0.5
    return ucb

In [ ]:
def monteCarlo():
